# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

#ghname: Java CI with Gradle

#ghon:
#gh  push:
#gh    branches: [ master ]
#gh  pull_request:
#gh    branches: [ master ]

#ghjobs:
#gh  build:

#gh    name: Build on Java ${{ matrix.java-version }}
#gh    runs-on: ubuntu-latest
#gh    strategy:
#gh      matrix:
#gh        java-version: [1.8, 11, 14]

#gh    steps:
#gh      - name: Checkout
#gh        uses: actions/checkout@v2
#gh      - name: Set up JDK ${{ matrix.java-version }}
#gh        uses: actions/setup-java@v1
#gh        with:
#gh          java-version: {{ matrix.java-version }}

#gh      - name: Grant execute permission for gradlew
#gh        run: chmod +x gradlew

#gh      - name: Build with Gradle
#gh        run: ./gradlew build

#gh      - name: Rename artifacts
#gh        run: for f in build/libs/*.jar; do mv "$f" "$(echo "$f" | sed s/.jar/+build-${{ github.run_number }}.jar/); done

#gh      - name: Upload Artifacts
#gh        uses: actions/upload-artifact@v2
#gh        if: success()
#gh        with:
#gh          path: build/libs
